AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Update RDS database with stats on new packs and cards openings

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: EDGE
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  PopulatePackStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.zerotoheroes.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-save-pack-received-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - SecretsManagerReadWrite
      Timeout: 90
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PopulatePackStatsApi:
    Description: URL to post pack stats
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/packstats'
    Export:
      Name: PopulatePackStatsApi